### ISSUE TITLE
non-numeric argument in a binary operator

### ISSUE THREAD

**Issue by HuTaoJiaZiAckerman** [cran/RZooRoH#2]
Hello, 

I get a message when I run this code.

This code is available from [here](https://github.com/rtfcoimbra/Coimbra-et-al-2021_CurrBiol/blob/main/estimate_roh.R). 

```
# command
library(RZooRoH)
setwd("~/17.ROH/")
data <- zoodata(genofile = "./04.vcf/snps.filtered.gen",zformat = "gp",samplefile = "./04.vcf/snps.filtered.samples")
# error message
[1] "Number of positions in original file ::"
[2] "27420024"                               
Error in g11 + g12 : 二进列运算符中有非数值参数
```

Could you tell me I should how get right input file. I guess that this file is need to flter some site, and you could give me some effective methods? 

Note: I‘m  sorry some message include Chinese character, because system is Ubuntu from China.  This message mean: 
```
二进列运算符中有非数值参数 ==> There is a non-numeric argument in a binary operator
```

**Comment by HuTaoJiaZiAckerman** [comment]
I solve this problem.the 


The PLINK can convert `file.bim` to OxfordGENFormat file.

I use code follwing:
```
plink -bfile snps.qc.ld -recode oxford -autosome -out snps.qc.ld
```

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by Banthandor** [comment]
>I solve this problem

Hi,
Did you manage to load the data with 27 million SNPs or did you need to reduce the size of the dataset? I have no clue what is a reasonable number of SNPs to use for this analysis.
Kind regards,
Sam
